apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-app-rollout
spec:
  replicas: 4
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app-container
        image: nginx:1.19.10
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
      - analysis:
          templates:
          - templateName: resource-usage-analysis
          args:
          - name: required-pod-count
            value: "3"
      - setWeight: 50
      - pause: {duration: 20s}
      - analysis:
          templates:
          - templateName: resource-usage-analysis
          args:
          - name: required-pod-count
            value: "3"
      - setWeight: 100
